### ISSUE TITLE
Where do you keep certificate files?

### ISSUE THREAD

**Issue by thesobercoder** [golang-standards/project-layout#126]
It's not clear where the `*.crt` files go. Please help.

**Comment by shivamarora1** [comment]
*.crt files can be used by different projects i.e. Suppose you have SSL certificates which make your website secure(HTTPS), So these certificates are accessible by different projects hosted into your server. Best thing would be to place these certificate inside /etc/ssl/{{certificate-name}} then inside ".config" file placed into "/config" folder make a new key "sslCerts":{{PATH_OF_CERTIFICATES}} so that certificates can be used by any application into your server.

**Comment by thesobercoder** [comment]
@shivamarora1 What I was asking was in the project layout where do I keep them?

**Comment by shivamarora1** [comment]
@thesobercoder You can create **/certs** directory on root of your project and place all ***.certs** file inside that, but just make sure include **/certs** directory in .gitignore file
